In [ ]:
import numpy as np

In [ ]:
# Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Create an array of 10 fives
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Create an array of the integers from 10 to 50
arr = np.arange(10,51)

In [ ]:
# Create an array of all the even integers from 10 to 50
# map((lambda x:x%2==0), arr) # didnt covert to list


In [ ]:
list(map((lambda x:x%2==0), arr))

[np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_,
 np.False_,
 np.True_]

In [ ]:
# Create a 3x3 matrix with values ranging from 0 to 8
mat = np.arange(0,9)

In [ ]:
mat.reshape(3,3) # didnt assign to a var

NameError: name 'mat' is not defined

In [ ]:
mat = mat.reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
mat1 = np.identity(3)
mat1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Use NumPy to generate a random number between 0 and 1
np.random.rand()

0.17432301180635312

In [ ]:
# Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([-0.4021074 ,  0.04906332, -2.15213561, -0.74317453, -0.92902071,
       -0.31962888, -0.78837072,  0.26483902,  1.57154562,  1.77641219,
       -0.74948881,  0.16321467, -2.08624253,  0.65657225, -0.29679943,
       -0.68766666,  1.16446713,  0.9075183 ,  1.09400687,  1.41947499,
       -0.93116129, -0.69943667,  0.99020435, -0.46409399, -1.60129904])

In [ ]:
# Create the following matrix:
np.arange(0.01, 1.01, 0.01).reshape(10, 10)


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [ ]:
np.linspace(0,1.01,20)

array([0.        , 0.05315789, 0.10631579, 0.15947368, 0.21263158,
       0.26578947, 0.31894737, 0.37210526, 0.42526316, 0.47842105,
       0.53157895, 0.58473684, 0.63789474, 0.69105263, 0.74421053,
       0.79736842, 0.85052632, 0.90368421, 0.95684211, 1.01      ])

In [ ]:
# Indexing

In [ ]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
arr[3:4,4:5]

array([[20]])

In [ ]:
arr[3,4]

np.int64(20)

In [ ]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# operations

In [ ]:
arr.sum()

np.int64(325)